// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5kOVvN3XX8zy6LAnuKRW8EHFuaF2GBc4',
    appId: '1:642343302890:web:e7b2384251381f20b40993',
    messagingSenderId: '642343302890',
    projectId: 'kezmarc-app-6328e',
    authDomain: 'kezmarc-app-6328e.firebaseapp.com',
    storageBucket: 'kezmarc-app-6328e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBENkyhv3Ms7hhp_T9wl8MP4eN6CDE4YlY',
    appId: '1:642343302890:android:f24b05d6c42b4916b40993',
    messagingSenderId: '642343302890',
    projectId: 'kezmarc-app-6328e',
    storageBucket: 'kezmarc-app-6328e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5skmaYaoTzNCyzP3njDG67EiB9ZXRVss',
    appId: '1:642343302890:ios:5d72cf49fe0b380ab40993',
    messagingSenderId: '642343302890',
    projectId: 'kezmarc-app-6328e',
    storageBucket: 'kezmarc-app-6328e.appspot.com',
    iosClientId: '642343302890-2m83a4u40c88j4t2c1fspni5sev6hj6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5skmaYaoTzNCyzP3njDG67EiB9ZXRVss',
    appId: '1:642343302890:ios:5d72cf49fe0b380ab40993',
    messagingSenderId: '642343302890',
    projectId: 'kezmarc-app-6328e',
    storageBucket: 'kezmarc-app-6328e.appspot.com',
    iosClientId: '642343302890-2m83a4u40c88j4t2c1fspni5sev6hj6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );
}
